name: Manual-Release

env:
  GH_TOKEN: ${{ github.token }}

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: "Release type:"
        required: true
        options:
          - bug fix (PATCH)
          - new feature (MINOR)
      release_title:
        description: "The title of the release"
        required: true

jobs:
  update-version:
    runs-on: ubuntu-20.04 # latest
    permissions:
      contents: write # allow push

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Make new release
      run: |
        export release_title_sanitized=$(echo ${github.event.inputs.release_title//[\"]\\\"})
        $release_title_sanitized=$(echo ${release_title_sanitized//[\']\\\'})
        $release_title_sanitized=$(echo ${release_title_sanitized//[\$]/})
        ./publish-release.sh "${{ github.event.inputs.release_type }}" "${{ release_title_sanitized }}"
