name: Manual-Release

env:
  GH_TOKEN: ${{ github.token }}

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: "The type of release to make (Minor, Patch, etc)"
        required: true
        options:
          - PATCH
          - MINOR
      release_title:
        description: "The title of the release"
        required: true
      pre_release:
        type: boolean
        description: "Is this release a pre-release?"
        required: false
        default: false

jobs:
  update-version:
    runs-on: ubuntu-20.04 # latest
    permissions:
      contents: write # allow push
      pull-requests: write # allow making and merging PR

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Test Output
      run: |
        ./update-version.sh "${{ github.event.inputs.release_type }}" "${{ github.event.inputs.release_title }}" "${{ github.event.inputs.pre_release }}"

        echo "Testing that VERSION file exists..."
        echo $(cat VERSION)
